/-
Copyright (c) 2026 Paul Lezeau. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Paul Lezeau
-/
import QLean.Foundation.QMat
import Cslib

/-!
# The Quantum Program Monad (QProg)

We use a **deep embedding**: quantum programs are represented as an inductive data type `QProg`,
and their semantics is given by a separate denotation function. The register size is fixed in the
program type, while measurements and classical state updates are interpreted by the denotational
semantics below.

## Design

The `QProg` monad is parameterised by a fixed qubit count `n` and a user classical state
type `σ`. Primitive operations are generated by `QProg.Prim σ n`, and programs are
the free monad over that signature.

### Key types

* `QProg σ n α` — a quantum program over `n` qubits and user classical state `σ`, returning `α`.
* `QProg.Prim σ n α` — the primitive operation signature.
* `QProg.Exec n α` — a finite-support classical-quantum state whose labels have type `α`.
* `QProg.ExecM n σ α` — the execution monad used to interpret programs.
* `QMat n` — full-register matrices indexed by computational-basis bitstrings.

### Primitives

| Primitive | Type | Effect |
|-----------|------|--------|
| `applyUnitary` | `QMat n → QProg σ n Unit` | Apply a unitary to the full register |
| `applyClassical` | `(σ → σ) → QProg σ n Unit` | Update the user classical state |
| `readClassical` | `QProg σ n σ` | Read the user classical state |
| `meas` | `Fin n → QProg σ n Bool` | Measure qubit `i` and return the measured bit |
| `pure` | `α → QProg σ n α` | Return a classical value |
| `bind` | `QProg σ n α → (α → QProg σ n β) → QProg σ n β` | Sequence programs |
-/

namespace QLean

noncomputable section

open scoped Matrix ComplexOrder

/-! ## Deep Embedding: Program Syntax -/

/-- `QProg σ n α` is the type of fixed-register quantum programs over `n` qubits with user
    classical state type `σ`, returning a value of type `α`.

    This is a free monad / deep embedding — no semantics yet, just syntax. -/
inductive QProg.Prim (σ : Type) (n : ℕ) : Type → Type where
  /-- Apply a unitary operator to the full `n`-qubit register. -/
  | applyUnitary (U : QMat n) (hU : U.Unitary) :
      QProg.Prim σ n Unit
  /-- Apply a deterministic update to the user classical state. -/
  | applyClassical (f : σ → σ) :
      QProg.Prim σ n Unit
  /-- Read the current user classical state. -/
  | readClassical :
      QProg.Prim σ n σ
  /-- Measure qubit `target` in the computational basis.
      Returns `true` for `|1⟩`, `false` for `|0⟩`. -/
  | meas (target : Fin n) :
      QProg.Prim σ n Bool


abbrev QProg (σ : Type) (n : ℕ) := Cslib.FreeM <| QProg.Prim σ n

namespace QProg

abbrev Program (σ : Type) (n : ℕ) (α : Type) := QProg σ n α

/-! ## Execution Semantics -/

/--
`Exec n α` is a finite-support classical-quantum state.

A branch label `a : α` carries a subnormalized density matrix.
The trace of that matrix is the probability weight of the branch.
Measurements therefore branch by producing `P₀ ρ P₀` and `P₁ ρ P₁`,
without normalizing either branch.
-/
abbrev Exec (n : ℕ) (α : Type) := α →₀ QMat n

namespace Exec

/-- Place a quantum matrix at a single classical branch label. -/
def pureBranch {n : ℕ} {α : Type} (a : α) (ρ : QMat n) : Exec n α :=
  Finsupp.single a ρ

/-- Compose finite classical branching while threading the branch quantum matrix. -/
def bind {n : ℕ} {α β : Type} (μ : Exec n α)
    (K : α → QMat n → Exec n β) : Exec n β :=
  μ.sum fun a ρ => K a ρ

/-- Apply a quantum matrix operation to every branch. -/
def mapQuantum {n : ℕ} {α : Type} (φ : QMat n → QMat n) (hφ : φ 0 = 0)
    (μ : Exec n α) : Exec n α :=
  μ.mapRange φ hφ

/-- Push classical branch labels forward, adding matrices when labels collide. -/
def push {n : ℕ} {α β : Type} (f : α → β) (μ : Exec n α) : Exec n β :=
  Finsupp.mapDomain f μ

/-- The branchwise action of a unitary on a density matrix. -/
def evolve {n : ℕ} (U : QMat n) (ρ : QMat n) : QMat n :=
  QMat.evolve U ρ

/-- Apply a unitary to every quantum branch. -/
def applyUnitary {n : ℕ} {α : Type} (U : QMat n) (μ : Exec n α) : Exec n α :=
  mapQuantum (evolve U) (by simp [evolve, QMat.evolve]) μ

/-- Branch a single classical label according to a computational-basis measurement. -/
def measBranch {n : ℕ} {α : Type} (target : Fin n) (a : α) (ρ : QMat n) :
    Exec n (α × Bool) :=
  Finsupp.single (a, false)
      (QMat.measProjector target false * ρ * QMat.measProjector target false) +
    Finsupp.single (a, true)
      (QMat.measProjector target true * ρ * QMat.measProjector target true)

/-- Branch every classical label according to a computational-basis measurement. -/
def meas {n : ℕ} {α : Type} (target : Fin n) (μ : Exec n α) : Exec n (α × Bool) :=
  μ.sum fun a ρ => measBranch target a ρ

end Exec

/-- The execution monad for fixed-register classical/quantum configurations. -/
abbrev ExecM (n : ℕ) (σ : Type) (α : Type) := σ → QMat n → Exec n (σ × α)

namespace ExecM

/-- Return a value without changing the classical or quantum state. -/
def pure {n : ℕ} {σ α : Type} (a : α) : ExecM n σ α :=
  fun s ρ => Exec.pureBranch (s, a) ρ

/-- Sequence execution computations, feeding returned values to the continuation. -/
def bind {n : ℕ} {σ α β : Type} (x : ExecM n σ α)
    (K : α → ExecM n σ β) : ExecM n σ β :=
  fun s ρ =>
    Exec.bind (x s ρ) fun sa ρ' =>
      K sa.2 sa.1 ρ'

instance {n : ℕ} {σ : Type} : Monad (ExecM n σ) where
  pure := pure
  bind := bind
  map f x := bind x fun a => pure (f a)
  seq f x := bind f fun g => bind (x ()) fun a => pure (g a)

/-- Run an execution computation on one classical-quantum branch. -/
def run {n : ℕ} {σ α : Type} (x : ExecM n σ α) (s : σ) (ρ : QMat n) :
    Exec n (σ × α) :=
  x s ρ

/-- Run an execution computation over a finite-support initial classical-quantum state. -/
def runOn {n : ℕ} {σ α : Type} (x : ExecM n σ α) (μ : Exec n σ) :
    Exec n (σ × α) :=
  Exec.bind μ fun s ρ => x s ρ

end ExecM

/-- Denotation of one primitive operation in the execution monad. -/
noncomputable def denotePrim {n : ℕ} {σ : Type} {α : Type} :
    QProg.Prim σ n α → ExecM n σ α
  | QProg.Prim.applyUnitary U _hU =>
      fun s ρ => Exec.pureBranch (s, ()) (Exec.evolve U ρ)
  | QProg.Prim.applyClassical f =>
      fun s ρ => Exec.pureBranch (f s, ()) ρ
  | QProg.Prim.readClassical =>
      fun s ρ => Exec.pureBranch (s, s) ρ
  | QProg.Prim.meas target =>
      fun s ρ => Exec.measBranch target s ρ

/-- Monadic denotational semantics of a `QProg` program. -/
noncomputable def denote {n : ℕ} {σ : Type} {α : Type} :
    QProg σ n α → ExecM n σ α :=
  Cslib.FreeM.liftM (fun {ι} (op : QProg.Prim σ n ι) => denotePrim op)

/-- Denotational semantics over a finite-support initial classical-quantum state. -/
noncomputable def denoteOn {n : ℕ} {σ : Type} {α : Type}
    (prog : QProg σ n α) (μ : Exec n σ) : Exec n (σ × α) :=
  ExecM.runOn (denote prog) μ

/-! ## Monadic Interface -/

instance {σ n} : Monad (QProg σ n) := inferInstance

/-! ## Core Combinators -/

/-- Apply a proved-unitary full-register matrix to the quantum register. -/
def applyUnitary {σ : Type} {n : ℕ} (U : QMat n) (hU : U.Unitary) : QProg σ n Unit :=
  Cslib.FreeM.lift (QProg.Prim.applyUnitary U hU)

/-- Update the user classical state. -/
def applyClassical {σ : Type} {n : ℕ} (f : σ → σ) : QProg σ n Unit :=
  Cslib.FreeM.lift (QProg.Prim.applyClassical f)

/-- Return the current user classical state. -/
def readClassical {σ : Type} {n : ℕ} : QProg σ n σ :=
  Cslib.FreeM.lift (QProg.Prim.readClassical)

/-- Measure one qubit in the computational basis and return the outcome. -/
def meas {σ : Type} {n : ℕ} (target : Fin n) : QProg σ n Bool :=
  Cslib.FreeM.lift (QProg.Prim.meas target)

end QProg

end

end QLean
